
# ========== Create user with duplicate email ===============
POST http://localhost:8080/api/users/register HTTP/1.1
Content-Type: application/json

{
    "name": "johndoe",
    "email": "johndoe@gmail.com", 
    "password": "12345678" 
}


###
# ========== Create new user  ===============
POST http://localhost:8080/api/users/register HTTP/1.1
Content-Type: application/json

{
    "name": "oung",
    "email": "oung@gmail.com", 
    "password": "12345678" 
}

###
# ========== Create new user with invalid inputs  ===============
POST http://localhost:8080/api/users/register HTTP/1.1
Content-Type: application/json

{
    "name": "oung",
    "email": "oung.com", 
    "password": "12345678" 
}